apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: headlamp
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/apps/headlamp
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
