apiVersion: v1
kind: Service
metadata:
  name: vrising-pvp
  annotations:
    io.cilium/lb-ipam-ips: "192.168.253.153"
spec:
  type: LoadBalancer
  selector:
    app: vrising-pvp
  ports:
  - name: game
    port: 9876
    targetPort: game
    protocol: UDP
  - name: query
    port: 9877
    targetPort: query
    protocol: UDP