apiVersion: v1
kind: Service
metadata:
  name: teamspeak
  annotations:
    io.cilium/lb-ipam-ips: 192.168.253.198
spec:
  ports:
  - name: file
    port: 30033
    protocol: TCP
    targetPort: file
  - name: query
    port: 10011
    protocol: TCP
    targetPort: query
  - name: voice
    port: 9987
    protocol: UDP
    targetPort: voice
  selector:
    app: teamspeak
    part-of: teamspeak
  type: LoadBalancer
