apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: srv-manager
rules:
- apiGroups: [""]
  resources: ["namespaces", "nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["watch","list"]
- apiGroups: ["instancetype.kubevirt.io", "migrations.kubevirt.io"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-srv-manager
roleRef:
  kind: ClusterRole
  name: srv-manager
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: "'oidc:'servers-manager"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: srv-manager
  namespace: palworld
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["*"]
  resources: ["deployments", "pods", "replicasets", "services", "ingresses"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc-srv-manager
  namespace: palworld
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: srv-manager
subjects:
- kind: Group
  name: "'oidc:'servers-manager"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: srv-manager
  namespace: multipaper
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc-srv-manager
  namespace: multipaper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: srv-manager
subjects:
- kind: Group
  name: "'oidc:'servers-manager"
