apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault
  namespace: vault
spec:
  secretName: server-cert
  duration: 70126h # 8y
  renewBefore: 360h # 15d
  subject:
    organizations:
      - LogicMG
  commonName: vault.logicmg.intra
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - vault.logicmg.intra
  issuerRef:
    name: root-logicmg
    kind: ClusterIssuer
    group: cert-manager.io