server:
  dataStorage:
    enabled: true
    size: 6Gi
    mountPath: "/vault/data"
    storageClass: longhorn
    accessMode: ReadWriteOnce
    annotations:
      nfs.io/storage-path: "data01/vault"
  standalone:
    enabled: "-"
  ha:
    enabled: false
    replicas: 1
    raft:
      enabled: false
  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false

ui:
  enabled: true
  publishNotReadyAddresses: true
  activeVaultPodOnly: false
  serviceType: "Load"
  externalPort: 8200
  targetPort: 8200

injector:
  enabled: false
  
csi:
  enabled: false
