apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://192.168.253.152"
      path: "secrets"
      version: "v2"
      caProvider:
        type: Secret
        name: logicmg-ca
        namespace: vault-unsealer-operator-system
        key: ca.crt
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "vault-auth"
            namespace: "external-secrets"
