apiVersion: v1
kind: Service
metadata:
  name: minio
  annotations:
    io.cilium/lb-ipam-ips: "192.168.253.153"
spec:
  type: LoadBalancer
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: http
    protocol: TCP
