apiVersion: v1
kind: Service
metadata:
  name: minio
  annotations:
    io.cilium/lb-ipam-ips: "192.168.253.153"
spec:
  type: LoadBalancer
  selector:
    app: minio
  ports:
  - name: api
    port: 9000
    targetPort: api
  - name: console
    port: 9001
    targetPort: console
